### ISSUE TITLE
Update for latest python-dateutil 2.4.2

### ISSUE THREAD

**Issue by protist** [jspricke/remind-caldav#1]
Hi,

I'm trying to get `dav2rem` running, and I'm hitting the following error. 
```
$ dav2rem
Traceback (most recent call last):
  File "/usr/bin/dav2rem", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.4.2 (/usr/lib/python2.7/site-packages), Requirement.parse('python-dateutil<2.4'), set(['remind']))
```
I guess it needs to be updated to work with the latest version of python-dateutil, i.e. [2.4.2](https://pypi.python.org/pypi/python-dateutil/)?

**Comment by jspricke** [comment]
That was because of a bug in python-dateutil 2.4.0, which seems to be fixed now. I've pushed a new version of python-remind, can you give it a try?

**Comment by protist** [comment]
Thank you, it appears to work fine now. However, I have a couple of other issues. I'm happy to open up new threads if you like.

1. I was considering running dav2rem (and rem2dav) from a script. Is there a way to store the password in (say) [python-keyring](https://pypi.python.org/pypi/keyring), so that I don't need to manually type it in? (I was considering running it from a cron job and/or just before/after wyrd.)
2. `dav2rem` seems to fail on self-signed certificates anyway.
```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by jspricke** [comment]
I would propose to use email, but I can answer here for now.
1. There is support for `.netrc`. Adding python-keyring should be easy. Can you send a patch?
2. I'm relying in [python-caldav](https://pypi.python.org/pypi/caldav/) and I guess it's again relying on openssl, so I guess you need to add your certificate to `/etc/ssl`.

**Comment by protist** [comment]
1. Unfortunately, I don't know how to code in python at all. Is there no way to even hardcode the password in a script or config file, if I encrypted the file? Is there any way at all to run dav2rem from a script (i.e. non-interactively)?
2. I had to test a few different scenarios, but I found one that worked. There is a symlink at `/etc/ssl/cert.pem` that points to `/etc/ca-certificates/extracted/tls-ca-bundle.pem`. I could manually append my certificate to the target, which fixed the problem.

Unfortunately I'm having other problems now, so I'll email you as a follow up. Thank you for your help so far!

**Comment by jspricke** [comment]
Hi Lee,

* protist <notifications@github.com> [2015-10-14 04:33]:
> 1. Unfortunately, I don't know how to code in python at all. Is there no way to even hardcode the password in a script or config file, if I encrypted the file? Is there any way at all to run dav2rem from a script (i.e. non-interactively)?

With netrc you can do exactly that. Have a look at the documentation
here:
http://mavetju.org/unix/netrc.php

But the python-keyring idea is still good. Would you be able to test it,
if I send you a custom version?

> I did manage to get dav2rem running partially. It synced about 9 events, then failed, with the error below. Please let me know if there is anything else I can do to troubleshoot.
> 
> $ dav2rem -r https://foo.com/owncloud/remote.php/caldav/ -u bar
> Password: /usr/lib/python2.7/site-packages/urllib3/connection.py:264:
> SubjectAltNameWarning: Certificate for foo.com has no `subjectAltName`,
> falling back to check for a `commonName` for now. This feature is being
> removed by major browsers and deprecated by RFC 2818. (See
> https://github.com/shazow/urllib3/issues/497 for details.)
>  SubjectAltNameWarning

I guess you need to fix your certificate and add a subjectAltName filed.

Cheers Jochen

**Comment by jspricke** [comment]
Closing here, as the original problem is fixed and we continue over mail.
