### ISSUE TITLE
rem2dav is not deleting events deleted from reminder file

### ISSUE THREAD

**Issue by danielsouzat** [jspricke/remind-caldav#10]
Let's say I have the events bellow and I sync them with rem2dav to a new Radicale calendar.

```
REM Jul 22 2020 MSG Do A
REM Jul 23 2020 MSG Do B
```
Later I edit the .rem file to be as bellow and resync it.

```
REM Jul 23 2020 MSG Do B
REM Jul 24 2020 MSG Do C
```

When I sync it back with dav2rem, instead of getting the above I get the bellow.

```
REM Jul 22 2020 MSG Do A
REM Jul 23 2020 MSG Do B
REM Jul 24 2020 MSG Do C
```

**Comment by jspricke** [comment]
Did you use `rem2dav --delete`?

**Comment by danielsouzat** [comment]
Sorry, I missed it. Indeed it will delete when I use -d . But does that means it is not possible to sync events between devices using rem2dav and dav2rem? As rem2dav -d apparently just overwrite everything.

**Comment by jspricke** [comment]
dav2rem does not preserve the ical UIDs so it's not really possible to do a two way sync.
