### ISSUE TITLE
Can't sync with google

### ISSUE THREAD

**Issue by Barbaross93** [jspricke/remind-caldav#17]
I've been trying to get `rem2dav` to interact with my google calendar but at every attempt I get an "Unauthorized" error. At this point, I'm not sure what I'm suppose to be using for credentials. Do I need to use a client ID & client password or will my google login information work? According to the docs from google, it looks like the new dav URL is `https://apidata.googleusercontent.com/caldav/v2/calid/user` so I assume that part (with `calid` properly replaced) is correct.  I do have the less secure apps enabled as well.I did see while enabling it that that option will be removed starting May 30th, so it seems an alternative will be needed?

Sorry, I'm at my wit's end with this. If you need any more info from me I'll provide it.

**Comment by jspricke** [comment]
Given that Google will disable the service anyhow I don't think it makes sense to debug it.

There is a upstream issue here: https://github.com/python-caldav/caldav/issues/119

Maybe it would be easier to use a different CalDAV provider (I don't use Google so I will not work on this).

**Comment by Barbaross93** [comment]
That makes sense. I went ahead and setup your other project `radicale-remind` and everything works. The only minor annoyance I have is that I think I have to use something like unison or synching to sync the files from my laptop  to my raspberry pi where the radicale server is located. At least with this project I could do `rem2dav ... ~/.reminders` from my laptop, which feels more convenient to me. Do you have suggestions to go about this?

**Comment by Barbaross93** [comment]
Here's the specific error I'm getting:
```
Traceback (most recent call last):
  File "/home/barbaross/.local/pipx/.cache/cfad4f428d5cd1c/bin/rem2dav", line 8, in <module>
    sys.exit(main())
  File "/home/barbaross/.local/pipx/.cache/cfad4f428d5cd1c/lib/python3.10/site-packages/rem2dav.py", line 130, in main
    for event in calendar.events()
  File "/home/barbaross/.local/pipx/.cache/cfad4f428d5cd1c/lib/python3.10/site-packages/caldav/objects.py", line 1036, in events
    return self.search(root, comp_class=Event)
  File "/home/barbaross/.local/pipx/.cache/cfad4f428d5cd1c/lib/python3.10/site-packages/caldav/objects.py", line 785, in search
    (response, objects) = self._request_report_build_resultlist(xml, comp_class)
  File "/home/barbaross/.local/pipx/.cache/cfad4f428d5cd1c/lib/python3.10/site-packages/caldav/objects.py", line 752, in _request_report_build_resultlist
    response = self._query(xml, 1, 'report')
  File "/home/barbaross/.local/pipx/.cache/cfad4f428d5cd1c/lib/python3.10/site-packages/caldav/objects.py", line 166, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
caldav.lib.error.ReportError: ReportError at '500 Internal Server Error

b'A server error occurred.  Please contact the administrator.'', reason 'no reason'
```

**Comment by Barbaross93** [comment]
> I have a raspberry like arm that is running wyrd for the calendar and other tools in a tmux and I connect to it via ssh from everywhere. I also use unison to sync my $HOME to my laptop and I use radicale-remind to sync to my Android. You can read more on my setup here: https://jochen.sprickerhof.de/Software/Dotfiles/ And I'm happy to share more insights.

Keeping wyrd/mutt/abook on the server and accessing through ssh is not a bad idea at all. I'll have to think about whether this makes sense for me.

Haha, the only reason why I'm bothering with `radicale-remind` is so that I can get reminders on my android as well :) (DAVx5 ftw! I didn't realize it could integrate with the Google calendar app!)

> I use the .reminders file as my ground truth and use it's advanced features and functions quiet a bit. I tried to convert some of them to CalDAV but the conversion is not perfect. So I would advice against using rem2dav for syncing. I never tried synching but I guess it should work well.

Yeah, I was beginning to realize that if I'm using my phone to create events, `radicale-remind` makes more sense for the 2-way syncing. I think I'll just be happy with it instead of trying to oversimplify the setup.

> What setup is this? If you try rem2dav against radicale-remind then you could start radicale -D to get the debugging output on the server.

This was me running 
```
pipx run --spec remind-caldav rem2dav -r <URL> -u <USER> -p <PASSWORD> ~/.reminders
```
from my laptop against `radicale-remind`. While that makes sense to check debug output from radicale, I think I'll just stick with `radicale-remind`.

Thanks for all of your help and for the amazing helper tools you've made done for `remind`!
