### ISSUE TITLE
Special tag for event status

### ISSUE THREAD

**Issue by walderich** [jspricke/remind-caldav#21]
I am adding my colleagues vacation to my work reminders so that I know when they are not available. But now it is hard to see if the event is important (like my own vacation) or not. Would it be possible to set the `VEVENT` status using custom TAGs according to the current classes handling? The status can be set to `TENTATIVE`, `CONFIRMED` or `CANCELLED` and Thunderbird dims `TENTATIVE` and crosses out `CANCELLED` events. This would also allow to keep cancelled meetings in the calendar.

**Comment by jspricke** [comment]
The underlying remind library already supports adding tags so it should be easy to lift this to remind-caldav. Do you want to send a PR?

**Comment by jspricke** [comment]
I think this can be closed, feel free to reply if there is more that needs to be done.
