### ISSUE TITLE
Clarification of --old and --delete options

### ISSUE THREAD

**Issue by tjex** [jspricke/remind-caldav#23]
I'm trying to figure out the safest workflow to sync calendars, while not keeping any redundant (deleted / changed) events on any client.

I have a feeling the `--old` flag is supposed to be used to some degree in a better syncing workflow, but I can't understand from the description what it does.

Am I supposed to reference an old remind file in a call to `rem2dav`, which will then delete all events that are not in the `remfile` used in the call? If so, I don't see any difference between this and the `--delete` option, which also deletes events from the dav that do not exist in the `remfile` used in the call.

`rem2dav --help`:
```text
  -o OLD, --old OLD     The old reference Remind file (entries not in the
                        current one will be deleted from dav)
```

Or could someone illustrate a use case for `--old`?

Once understanding this, I'm happy to make a PR making the help output more clear.

Also on the note of the `--delete` flag. "Old events" are here exclusively meant as deleted events from the client / caldav side, correct? I.e., it is not meaning "delete events that are older than x years/months/days", which would be more the literal undersanding.

```
  -d, --delete          Delete old events
```

As a side question, can I ask how you / others handle adding events via multiple clients and syncing without having to worry about whether the dav / client side has unpushed / unpulled changes, and would therefore delete events from the other side?..

**Comment by tjex** [comment]
Ok thanks for the clarifications. 
I've seen radicale-remind, but I'm not yet at the point of having my own public server. And I do want to be able to sync tasks when out and about, rather than just on local host.

**Comment by jspricke** [comment]
Using remind-caldav basically means that your ground truth is the ical on the server side so you would sync the remote data to a local remind file with dav2rem, view, edit it and sync it back with rem2dav. I like the remind syntax much more so I prefer having it as the ground truth, thus I developt radicale-remind and did not spend much time with remind-caldav.
